"""Inventory domain package."""

from app.domain.inventory.enums import (
    AdjustmentReason,
    InventoryCondition,
    InventoryItemStatus,
    InventoryStatus,
    InventorySyncStatus,
    MovementType,
    ReservationStatus,
    StockState,
    WarehouseType,
)
from app.domain.inventory.events import (
    INVENTORY_ADJUSTED,
    INVENTORY_CREATED,
    INVENTORY_LOW,
    INVENTORY_OUT_OF_STOCK,
    INVENTORY_RELEASED,
    INVENTORY_RESERVED,
    INVENTORY_TRANSFERRED,
    INVENTORY_UPDATED,
    RESERVATION_EXPIRED,
)
from app.domain.inventory.value_objects import (
    InventoryId,
    LocationCode,
    MovementId,
    Quantity,
    ReservationId,
    SKU,
    WarehouseCode,
)

__all__ = [
    "AdjustmentReason",
    "InventoryCondition",
    "InventoryId",
    "InventoryItemStatus",
    "InventoryStatus",
    "InventorySyncStatus",
    "LocationCode",
    "MovementId",
    "MovementType",
    "Quantity",
    "ReservationId",
    "ReservationStatus",
    "SKU",
    "StockState",
    "WarehouseCode",
    "WarehouseType",
    "INVENTORY_ADJUSTED",
    "INVENTORY_CREATED",
    "INVENTORY_LOW",
    "INVENTORY_OUT_OF_STOCK",
    "INVENTORY_RELEASED",
    "INVENTORY_RESERVED",
    "INVENTORY_TRANSFERRED",
    "INVENTORY_UPDATED",
    "RESERVATION_EXPIRED",
]
