"""Inventory domain events."""

INVENTORY_CREATED = "inventory.created"
INVENTORY_UPDATED = "inventory.updated"
INVENTORY_RESERVED = "inventory.reserved"
INVENTORY_RELEASED = "inventory.released"
INVENTORY_ADJUSTED = "inventory.adjusted"
INVENTORY_TRANSFERRED = "inventory.transferred"
INVENTORY_LOW = "inventory.low"
INVENTORY_OUT_OF_STOCK = "inventory.out_of_stock"
RESERVATION_EXPIRED = "reservation.expired"

INVENTORY_ITEM_CREATED = "inventory.item.created"
INVENTORY_ITEM_UPDATED = "inventory.item.updated"
INVENTORY_ITEM_ARCHIVED = "inventory.item.archived"
INVENTORY_QUANTITY_ADJUSTED = "inventory.quantity.adjusted"
INVENTORY_VALIDATED = "inventory.item.validated"
INVENTORY_EBAY_PUSH_SUCCEEDED = "inventory.ebay.push.succeeded"
INVENTORY_EBAY_PUSH_FAILED = "inventory.ebay.push.failed"
INVENTORY_EBAY_DELETED = "inventory.ebay.deleted"
INVENTORY_SYNC_RETRY = "inventory.sync.retry"
